@startuml Classes

class Dossier{
    - Patient:Patient




}

class Antecedent{
    - diagnostic:String?
    - traitement:String?
    - medecin:Medecin
    - debut : Optional<Date>
    - fin : Optional<Date>
}

class Visite{
    -Etablissement:String
    - medecin: Medecin
    - date: String
    - diagnostic: Optional<String>?
    - traitement: Optional<String>?
    - resume: String
    - notes: String
}

' class Etablissement{
    '     -nom:String
    '
'}


' class Carte{
    '     -numeroDossier
    '
'}

class Medecin{
    modifierDossier()


}

class Coordonnees{
    -adresse:String
    -telephone:String
    -courriel:String
}

class pasMedecin{}

class Patient{
    -nom:String
    -prenom:String
    -dateNaissance:String
    -genre:String
    -mere:String
    -pere:String
    -villeNaissance:String
    -coordonnees:Coordonnees
    -numeroAssuranceMaladie:String
    modifierCoordonnees()
    lireDossier()
}

abstract Utilisateur{
    lireDossier()
}

' class Diagnostic{
    ' -Medicament:String

    '
'}
' class Traitement{}



' Interface Consultable{


    '
'}

' Interface Modifiable{


    '
'}

baseDonnee *-- Dossier

Patient -- Utilisateur
Medecin -- Utilisateur
pasMedecin -- Utilisateur

' Visite -- Etablissement

' Dossier -- Consultable
' Dossier -- Modifiable

Dossier "1" o-- "0..*" Antecedent

Dossier "1" o-- "0..*" Visite
' Antecedent .. Medecin
' Visite .. Medecin

@enduml