@startuml composantes

title Composantes

actor "Employe RAMQ" as RAMQ
actor Medecin as M
actor Patient as P
actor "Professionnel non medical" as PM
[Application Medecin] as AM
[Site Web] as WWW
[Application Mobile] as MOB
database "Base de Donnees" as BD
[Systeme Dossier] as S

RAMQ -- AM
M -- AM
PM -- AM
P -- WWW
P -- MOB
S -- BD
MOB -down- S
AM - S
S - WWW


@enduml
