@startuml diagrammeDeploiement

actor Utilisateurs
cloud Internet
node Ordinateurs {
    node NavigateurWeb
    node LogicielDeGestion
    node ApplicationMobile
}
node ServeurWeb {
    component couchePrésentation
    component coucheLogique
}
database BaseDeDonnée {
    storage SQLite3
}

Utilisateurs --> Ordinateurs
Ordinateurs --> Internet
Internet --> ServeurWeb
ServeurWeb --> BaseDeDonnée

@enduml
