@startuml diagrammeDeploiement

Title Diagramme de Déploiement

actor Patient 
actor ProfessionnelMedical
actor EmployeRAMQ
cloud Internet
node Ordinateur {
    node LogicielDeGestion
}

node PC {
    node NavigateurWeb
}

node Telephone {
    node applicationMobile
}

node ServeurWeb {
    node couchePrésentation
}

node ServeurApplication {
    node coucheLogique
}

database BaseDeDonnée {
    storage SQLite3
}

Patient --> PC
Patient --> Telephone
ProfessionnelMedical --> Ordinateur
EmployeRAMQ --> Ordinateur
Ordinateur --> Internet
PC --> Internet
Telephone --> Internet
Internet --> ServeurWeb
ServeurWeb --> ServeurApplication
ServeurApplication --> BaseDeDonnée

@enduml
