@startuml EmployeRamqCreeDossier

Title Sequence - Création d'un dossier par un employé de la RAMQ

participant EmployeeRAMQ as ER
participant InterfaceUtilisateur as IU
participant SystemeDossier as SD 
participant Dossier as D 
participant Patient as P
participant Antecedent as A
participant Visite as V
participant Coordonnees as C
participant ConnecteurDB as CDB


ER -> IU : connexion(Identifiant)
activate ER
activate IU
IU -> SD : connexion(Identifiant)
activate SD

alt connexion etablie

  SD --> IU
  IU --> ER : connexion confirmee
  ER -> IU : creerDossier(info)
  IU -> SD : creerDossier(info)
  SD -> D : creerDossier(info)
  activate D
  D -> P : creerDossier(info)
 
  activate P
  P -> C : modifierCoordonnnees(info)
  activate C
  C --> P 
  deactivate C

  P -> A : creer()
  activate A
  A --> P 
  deactivate A

  P -> V : creer()
  activate V
  V --> P
  deactivate

  P --> D
  deactivate P

  D --> SD
  deactivate D

  SD -> CDB : ecrireBaseDonnees(dossier)
  activate CDB
  CDB --> SD
  deactivate CDB

  SD --> IU
  IU --> ER : confirmation

else connexion refusee

  SD --> IU 
  deactivate SD
  IU --> ER : connexion refusee
  deactivate IU
  deactivate ER

end


@enduml