@startuml

title Packages

package "Couche de présentation" #DDDDDD {
  abstract "InterfaceUtilisateur"{}
  class "SiteWeb"{}
  class "ApplicationMedecin"{}
  class "ApplicationMobile"{}
}

package "Couche logique" #DDDDDD  {
  class "SystemeDossier"
  class "Patient" {}
  class "Dossier" {}
  class "Antécédent" {}
  class "Visite" {}
  class "Médecin" {}
  class "Coordonées" {}
  class "ProfessionnelMédical" {}
  abstract "Utilisateur" {}
  class "Établissement" {}
  class "Hopital" {}
  class "Clinique" {}
  class "SalleEvaluation" {}
  class "PosteDeTravail" {}
  class "Identfiants" {}
  class "RAMQ" {}
  class "EmployeRAMQ" {}
  interface "Lisible" {}
  interface "Modifiable" {}
}

package "Couche donnees"  #DDDDDD  {
  class "ConnecteurDB" {}
}

database "Base de données" {
}


"Couche logique" ..> "Couche donnees"
"ConnecteurDB" ..> "Base de données"
"Couche de présentation" ..> "Couche logique"


@enduml
