@startuml sequenceModificationPatient

title Sequence - Modification des dossiers (Proxy)


participant InterfaceUtilisateur as U
participant SystemeDossier as S
participant ProxyDossier as PD
participant Dossier as D
participant ConnecteurDB as DB

U -> S: modifierDossier(info)
activate U
activate S
S -> PD: modifier(info)
activate PD
PD -> D: modifier(info)
activate D
D --> PD
deactivate D
PD --> S
deactivate PD
S -> DB: ecrireBaseDonnees(proxyDossier)
activate DB
DB --> PD: lire()
activate PD
PD --> D: lire()
activate D
D --> PD
deactivate D
PD --> DB
deactivate PD
DB --> S
deactivate DB
S --> U
deactivate S
deactivate U

@enduml

