@startuml UC2

title Modifier Coordonnees

actor Patient as U
participant “Interface Utilisateur” as IU
participant "Systeme Dossier Medical" as S
participant “Base de Donnees” as BD

U -> IU: Entrer numero dossier
IU -> S: Demande Dossier
S -> BD: Demande Dossier
BD --> S: Retour Dossier 
S --> IU: Retour Dossier
IU --> U : Affiche Dossier
U -> IU: Changement Coordonnees
IU -> S: Demande Changement Coordonnees
S -> BD: Demande Changement Coordonnees
BD --> S : Confirmation Changement
S --> IU : Confirmation Changement
IU --> U : Confirmation Changement

@enduml